# Generated by Django 5.2.8 on 2026-01-20 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('job_url', models.URLField(max_length=500, unique=True)),
                ('source', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
